### ISSUE TITLE
python apds-9930 library problem on raspberry pi 3

### ISSUE THREAD

**Issue by amir11111111** [Depau/APDS9930#11]
I have problem when i use python apds-9930 library i use your test program on github but i see this error on python shell 

```python
Traceback (most recent call last):
  File "/home/pi/apds-9930v1.py", line 10, in <module>
    a = APDS9930(busno)
  File "build/bdist.linux-armv7l/egg/apds9930/__init__.py", line 107, in __init__
    raise SensorError("Device ID not recognized: {0}".format(hex(self.id)))
SensorError: Device ID not recognized: 0x29
```

i use raspberry pi 3 

i think you can help me

and i have a question can use this library in python 3 

thank you

**Comment by depau** [comment]
This is the wrong repo 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️
https://github.com/Depaulicious/python-apds9930

**Comment by depau** [comment]
Anyway, you're either using the wrong device or have connection issues. If the value (`0x29`) is always the same, you're definitely using a different model.

The datasheet clearly states that the device should identify itself as 0x39:

[![Screenshot_from_2018-02-19_13-05-35.png](https://s14.postimg.org/rh2jclopd/Screenshot_from_2018-02-19_13-05-35.png)](https://postimg.org/image/wshfxbarx/)

If you're 10000000% sure you're using a 9930, you can try installing the Python module in development mode:

```shell
git clone https://github.com/Depaulicious/python-apds9930
cd python-apds9930
sudo pip install -e .
```
edit `values.py` and add `0x29` to `APDS9930_IDs` at [line 252](https://github.com/Depaulicious/python-apds9930/blob/master/apds9930/values.py#L252).

You should then test **ALL** the features and, if they work, report it to me so that I can add this unknown ID to both Arduino and Python libraries.

**Comment by amir11111111** [comment]
thank you it's worked for me but only print Proximity and Ambient light value is 0

**Comment by depau** [comment]
You need to enable the proximity sensor:
Docs: https://apds-9930-python-bindings.readthedocs.io/en/latest/#apds9930.APDS9930.enable_proximity_sensor
Code: https://github.com/Depaulicious/python-apds9930/blob/master/apds9930/__init__.py#L285

If it doesn't work even after enabling it you **DON'T HAVE** an APDS-9930. You have another sensor. That happens way too often on Chinese websites that put the wrong description to products. When I got my APDS-9930 I was actually expecting an APDS-9960 but they sent the wrong one.

Make sure that it works and that you get meaningful values and I'll consider adding the ID you provided to the libraries.

**Comment by amir11111111** [comment]
I think you're right because when i use this sensor on arduino Ambient sensor value is 0

i have problem with python 3 when i use python 3 i see this error 



Traceback (most recent call last):
  File "/home/pi/apds-9930v2.py", line 4, in <module>
    from apds9930 import APDS9930
  File "/usr/local/lib/python3.4/dist-packages/apds9930/__init__.py", line 584
    print "   REGISTER       DECIMAL  HEXADECIMAL     BINARY"
                                                            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by depau** [comment]
@amir11111111 The library was written years ago without Python 3 compatibility in mind. PRs are accepted if you're willing to port it to py3.

**Comment by amir11111111** [comment]
How can I do that?

**Comment by depau** [comment]
https://docs.python.org/3/howto/pyporting.html
